[project]
name = "stock_predictions"
version = "0.1.0"
description = "LSTM Model based stock price prediction"
readme = "README.md"
authors = [{name = "Amit Bakhru", email = "bakhru@me.com"}]
license = "MIT"
keywords = ["stock_predictions"]
requires-python = ">=3.9"
dependencies = [
    "bump2version",
    "watchdog",
    "coverage",
    "twine",
    "click",
    "yfinance",
    "pandas-datareader",
    "keras",
    "pydot",
    "graphviz",
    "alpha-vantage",
    "matplotlib",
    "arrow",
    "scikit-learn",
    "ruff",
    "isort",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9"
]
urls = { "Homepage" = "https://github.com/abakhru/stock_prediction" }

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "Q", "I"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.setuptools.packages.find]
where = ["stock_predictions"]
